# Generated by Django 5.2.5 on 2025-08-29 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buydetail',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_details', to='buys.buyheader'),
        ),
    ]
