# Generated by Django 5.2.5 on 2025-08-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0002_alter_buydetail_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyheader',
            old_name='obervaion',
            new_name='observation',
        ),
    ]
