# Generated by Django 5.2.5 on 2025-08-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0003_rename_obervaion_buyheader_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyheader',
            name='observation',
        ),
        migrations.AddField(
            model_name='buyheader',
            name='obervaion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buydetail',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buys.buyheader'),
        ),
    ]
