# Generated by Django 5.2.5 on 2025-08-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0004_remove_buyheader_observation_buyheader_obervaion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyheader',
            name='obervaion',
        ),
        migrations.AddField(
            model_name='buyheader',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buydetail',
            name='buy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_details', to='buys.buyheader'),
        ),
    ]
